<div class="follow-us container-fluid" align="centered">
  <div class="title text-center">
      <h1> FOLLOW US</h1>
      <p>__________</p>
  </div>
  <div class="social row">
    <div class="wrapper-social text-center">
      <div class="space-social col-sm-3 col-lg-2">
        <h6 class="insta">INSTAGRAM</h6>
      </div>
      <div class="space-social col-sm-3 col-md-2">
        <h6 class="fb">FACEBOOK</h6>
      </div>
      <div class="space-social col-sm-3 col-md-2">
        <h6 class="tw">TWITTER</h6>
      </div>
      <div class="space-social col-sm-3 col-md-3 col-lg-2">
        <h6 class="google">GOOGLE PLUS</h6>
      </div>
      <div class="col-md-2 col-md-3">
        <h6 class="pint">PINTEREST</h6>
      </div>
    </div>
  </div>
  <div class="follow-us-cta text-center">
    <input type="button" value="Read More">
  </div>
</div>
